config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :recipe_reviews

      resources :recipe_ingredients

      resources :recipes

      resources :inventory_of_food_items

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "inventory_of_food_items#index"
  resources :recipe_reviews
  resources :recipe_ingredients
  resources :recipes
  resources :inventory_of_food_items
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # Direct associations

  has_many   :recipe_comments,
             class_name: "RecipeReview",
             dependent: :destroy

  has_many   :recipe_ingredients,
             dependent: :destroy

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    recipe_name
  end
end

app/controllers/api/v1/recipes_controller.rb
class Api::V1::RecipesController < Api::V1::GraphitiController
  def index
    recipes = RecipeResource.all(params)
    respond_with(recipes)
  end

  def show
    recipe = RecipeResource.find(params)
    respond_with(recipe)
  end

  def create
    recipe = RecipeResource.build(params)

    if recipe.save
      render jsonapi: recipe, status: :created
    else
      render jsonapi_errors: recipe
    end
  end

  def update
    recipe = RecipeResource.find(params)

    if recipe.update_attributes
      render jsonapi: recipe
    else
      render jsonapi_errors: recipe
    end
  end

  def destroy
    recipe = RecipeResource.find(params)

    if recipe.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: recipe
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  def index
    @q = Recipe.ransack(params[:q])
    @recipes = @q.result(distinct: true).includes(:recipe_ingredients,
                                                  :recipe_comments).page(params[:page]).per(10)
  end

  def show
    @recipe_review = RecipeReview.new
    @recipe_ingredient = RecipeIngredient.new
  end

  def new
    @recipe = Recipe.new
  end

  def edit; end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: "Recipe was successfully created."
    else
      render :new
    end
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: "Recipe was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: "Recipe was successfully destroyed."
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:recipe_name, :servings, :cooking_time,
                                   :instructions)
  end
end

app/views/recipes/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Recipe #<%= recipe.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Recipe name</dt>
      <dd><%= recipe.recipe_name %></dd>

      <dt>Servings</dt>
      <dd><%= recipe.servings %></dd>

      <dt>Cooking time</dt>
      <dd><%= recipe.cooking_time %></dd>

      <dt>Instructions</dt>
      <dd><%= recipe.instructions %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back recipe, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_recipe_url(recipe), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to recipe, method: :delete, data: { confirm: "Do you really want to delete this recipe?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(recipe.updated_at) %> ago
  </div>
</div>

app/views/recipes/_form.html.erb
<% was_validated = recipe.errors.any? %>

<%= form_with(model: recipe, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% recipe_name_class = "form-control" %>
    <% recipe_name_was_invalid = recipe.errors.include?(:recipe_name) %>

    <% if was_validated %>
      <% if recipe_name_was_invalid %>
        <% recipe_name_class << " is-invalid" %>
      <% else %>
        <% recipe_name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :recipe_name %>
    <%= f.text_field :recipe_name, class: recipe_name_class, placeholder: "Enter recipe name" %>
    <% if recipe_name_was_invalid %>
      <% recipe.errors.full_messages_for(:recipe_name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% serving_class = "form-control" %>
    <% serving_was_invalid = recipe.errors.include?(:serving) %>

    <% if was_validated %>
      <% if serving_was_invalid %>
        <% serving_class << " is-invalid" %>
      <% else %>
        <% serving_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :servings %>
    <%= f.number_field :servings, class: serving_class, placeholder: "Enter serving" %>
    <% if serving_was_invalid %>
      <% recipe.errors.full_messages_for(:serving).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% cooking_time_class = "form-control" %>
    <% cooking_time_was_invalid = recipe.errors.include?(:cooking_time) %>

    <% if was_validated %>
      <% if cooking_time_was_invalid %>
        <% cooking_time_class << " is-invalid" %>
      <% else %>
        <% cooking_time_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :cooking_time %>
    <%= f.number_field :cooking_time, class: cooking_time_class, placeholder: "Enter cooking time" %>
    <% if cooking_time_was_invalid %>
      <% recipe.errors.full_messages_for(:cooking_time).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% instruction_class = "form-control" %>
    <% instruction_was_invalid = recipe.errors.include?(:instruction) %>

    <% if was_validated %>
      <% if instruction_was_invalid %>
        <% instruction_class << " is-invalid" %>
      <% else %>
        <% instruction_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :instructions %>
    <%= f.text_area :instructions, class: instruction_class, placeholder: "Enter instruction" %>
    <% if instruction_was_invalid %>
      <% recipe.errors.full_messages_for(:instruction).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/recipes/_list_item.html.erb
<%= link_to recipe, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= recipe %>
    <small class="text-muted">
      <%= time_ago_in_words(recipe.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/recipes/_recipe_recipe_comments.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Recipe Comments

    <a data-toggle="collapse" href="#recipe_recipe_comments_new_form">
      Add recipe review
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @recipe.recipe_comments.each do |recipe_review| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to recipe_review, recipe_review %>

        <% if current_user == recipe_review.commentor %>
          <%= link_to recipe_review, method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="recipe_recipe_comments_new_form">
        <%= render partial: "recipes/recipe_recipe_comments_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/recipes/_recipe_recipe_comments_new_form.html.erb
<%= form_with(model: @recipe_review, local: true) do |f| %>

  <%= f.hidden_field :reviewer_id, value: current_user.id %>

  <%= f.hidden_field :recipe_id, value: @recipe.id %>

  <div class="form-group">
    <%= f.label :rating %>

    <%= f.text_field :rating, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :review %>
    <%= f.text_area :review, rows: "3", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :recipe_name %>

    <%= f.text_field :recipe_name, class: "form-control" %>
  </div>

  <%= f.submit "Create recipe review", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/recipes/_recipe_recipe_ingredients.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Recipe Ingredients

    <a data-toggle="collapse" href="#recipe_recipe_ingredients_new_form">
      Add recipe ingredient
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to recipe_ingredient, recipe_ingredient %>

        <%= link_to recipe_ingredient, method: :delete, data: { confirm: "Do you really want to delete this recipe_ingredient" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="recipe_recipe_ingredients_new_form">
        <%= render partial: "recipes/recipe_recipe_ingredients_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/recipes/_recipe_recipe_ingredients_new_form.html.erb
<%= form_with(model: @recipe_ingredient, local: true) do |f| %>

  <%= f.hidden_field :recipe_id, value: @recipe.id %>

  <div class="form-group">
    <%= f.label :food_id %>

    <%= f.collection_select :food_id, InventoryOfFoodItem.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :ingredient_name %>

    <%= f.text_field :ingredient_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :quantity %>

    <%= f.text_field :quantity, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :quantity_units %>

    <%= f.select :quantity_units, options_for_select(RecipeIngredient.quantity_units.keys), {}, class: "form-control" %>
  </div>

  <%= f.submit "Create recipe ingredient", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/recipes/_recipes_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "recipes_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :recipe_name_cont, "Recipe name contains" %>
    <%= f.text_field :recipe_name_cont, :class => "form-control", :placeholder => "Recipe name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :instructions_cont, "Instructions contains" %>
    <%= f.text_field :instructions_cont, :class => "form-control", :placeholder => "Instructions contains" %>
  </div>

  <div class="form-group">
    <%= f.label :cooking_time, "Cooking time" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :cooking_time_gteq, :class => "form-control", :placeholder => "Cooking time greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :cooking_time_lteq, :class => "form-control", :placeholder => "Cooking time less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :servings, "Servings" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :servings_gteq, :class => "form-control", :placeholder => "Servings greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :servings_lteq, :class => "form-control", :placeholder => "Servings less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :recipe_ingredients_ingredient_name_cont, "Recipe ingredients ingredient_name contains" %>
    <%= f.text_field :recipe_ingredients_ingredient_name_cont, :class => "form-control", :placeholder => "Recipe ingredients ingredient_name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :recipe_comments_recipe_name_cont, "Recipe comments recipe_name contains" %>
    <%= f.text_field :recipe_comments_recipe_name_cont, :class => "form-control", :placeholder => "Recipe comments recipe_name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/recipes" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#recipes_filters">
  Show filters
</a>

app/views/recipes/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Recipe #<%= @recipe.id %>
      </h2>

      <div class="card-body">
        <%= render "form", recipe: @recipe %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Recipes

      <%= link_to new_recipe_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "recipes/recipes_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Recipes

        <%= link_to new_recipe_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @recipes, partial: "list_item", as: :recipe %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @recipes, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Recipe
      </h2>

      <div class="card-body">
        <%= render "form", recipe: @recipe %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @recipe, partial: "card", as: :recipe %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "recipes/recipe_recipe_ingredients" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "recipes/recipe_recipe_comments" %>
  </div>
</div>