config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :recipe_reviews

      resources :recipe_ingredients

      resources :recipes

      resources :inventory_of_food_items

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "inventory_of_food_items#index"
  resources :recipe_reviews
  resources :recipe_ingredients
  resources :recipes
  resources :inventory_of_food_items
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/inventory_of_food_item.rb
class InventoryOfFoodItem < ApplicationRecord
  enum purchased_status: { "need_to_purchase" => 0, "purchased" => 1 }

  # Direct associations

  has_many   :recipe_ingredients,
             foreign_key: "food_id",
             dependent: :nullify

  belongs_to :user

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    food_name
  end
end

app/controllers/api/v1/inventory_of_food_items_controller.rb
class Api::V1::InventoryOfFoodItemsController < Api::V1::GraphitiController
  def index
    inventory_of_food_items = InventoryOfFoodItemResource.all(params)
    respond_with(inventory_of_food_items)
  end

  def show
    inventory_of_food_item = InventoryOfFoodItemResource.find(params)
    respond_with(inventory_of_food_item)
  end

  def create
    inventory_of_food_item = InventoryOfFoodItemResource.build(params)

    if inventory_of_food_item.save
      render jsonapi: inventory_of_food_item, status: :created
    else
      render jsonapi_errors: inventory_of_food_item
    end
  end

  def update
    inventory_of_food_item = InventoryOfFoodItemResource.find(params)

    if inventory_of_food_item.update_attributes
      render jsonapi: inventory_of_food_item
    else
      render jsonapi_errors: inventory_of_food_item
    end
  end

  def destroy
    inventory_of_food_item = InventoryOfFoodItemResource.find(params)

    if inventory_of_food_item.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: inventory_of_food_item
    end
  end
end

app/controllers/inventory_of_food_items_controller.rb
class InventoryOfFoodItemsController < ApplicationController
  before_action :current_user_must_be_inventory_of_food_item_user,
                only: %i[edit update destroy]

  before_action :set_inventory_of_food_item,
                only: %i[show edit update destroy]

  def index
    @q = InventoryOfFoodItem.ransack(params[:q])
    @inventory_of_food_items = @q.result(distinct: true).includes(:user,
                                                                  :recipe_ingredients).page(params[:page]).per(10)
  end

  def show
    @recipe_ingredient = RecipeIngredient.new
  end

  def new
    @inventory_of_food_item = InventoryOfFoodItem.new
  end

  def edit; end

  def create
    @inventory_of_food_item = InventoryOfFoodItem.new(inventory_of_food_item_params)

    if @inventory_of_food_item.save
      message = "InventoryOfFoodItem was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @inventory_of_food_item, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @inventory_of_food_item.update(inventory_of_food_item_params)
      redirect_to @inventory_of_food_item,
                  notice: "Inventory of food item was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @inventory_of_food_item.destroy
    message = "InventoryOfFoodItem was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to inventory_of_food_items_url, notice: message
    end
  end

  private

  def current_user_must_be_inventory_of_food_item_user
    set_inventory_of_food_item
    unless current_user == @inventory_of_food_item.user
      redirect_back fallback_location: root_path,
                    alert: "You are not authorized for that."
    end
  end

  def set_inventory_of_food_item
    @inventory_of_food_item = InventoryOfFoodItem.find(params[:id])
  end

  def inventory_of_food_item_params
    params.require(:inventory_of_food_item).permit(:user_id, :date_purchased,
                                                   :expiration_date, :days_until_expiration, :purchased_status, :food_name, :note)
  end
end

app/views/inventory_of_food_items/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Inventory Of Food Item #<%= inventory_of_food_item.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>User</dt>
      <dd>
        <% if @inventory_of_food_item.user.present? %>
          <%= link_to inventory_of_food_item.user, inventory_of_food_item.user %>
        <% end %>
      </dd>

      <dt>Date purchased</dt>
      <dd><%= inventory_of_food_item.date_purchased %></dd>

      <dt>Expiration date</dt>
      <dd><%= inventory_of_food_item.expiration_date %></dd>

      <dt>Days until expiration</dt>
      <dd><%= inventory_of_food_item.days_until_expiration %></dd>

      <dt>Purchased status</dt>
      <dd><%= inventory_of_food_item.purchased_status %></dd>

      <dt>Food name</dt>
      <dd><%= inventory_of_food_item.food_name %></dd>

      <dt>Note</dt>
      <dd><%= inventory_of_food_item.note %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back inventory_of_food_item, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <% if current_user == @inventory_of_food_item.user %>
          <%= link_to edit_inventory_of_food_item_url(inventory_of_food_item), class: "btn btn-block btn-sm btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <% if current_user == @inventory_of_food_item.user %>
          <%= link_to inventory_of_food_item, method: :delete, data: { confirm: "Do you really want to delete this inventory_of_food_item?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(inventory_of_food_item.updated_at) %> ago
  </div>
</div>

app/views/inventory_of_food_items/_form.html.erb
<% was_validated = inventory_of_food_item.errors.any? %>

<%= form_with(model: inventory_of_food_item, local: true, novalidate: true, class: "mb-3") do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="form-group">
    <% date_purchased_class = "form-control" %>
    <% date_purchased_was_invalid = inventory_of_food_item.errors.include?(:date_purchased) %>

    <% if was_validated %>
      <% if date_purchased_was_invalid %>
        <% date_purchased_class << " is-invalid" %>
      <% else %>
        <% date_purchased_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :date_purchased %>
    <%= f.date_select :date_purchased, class: date_purchased_class, placeholder: "Enter date purchased" %>
    <% if date_purchased_was_invalid %>
      <% inventory_of_food_item.errors.full_messages_for(:date_purchased).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% expiration_date_class = "form-control" %>
    <% expiration_date_was_invalid = inventory_of_food_item.errors.include?(:expiration_date) %>

    <% if was_validated %>
      <% if expiration_date_was_invalid %>
        <% expiration_date_class << " is-invalid" %>
      <% else %>
        <% expiration_date_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :expiration_date %>
    <%= f.date_select :expiration_date, class: expiration_date_class, placeholder: "Enter expiration date" %>
    <% if expiration_date_was_invalid %>
      <% inventory_of_food_item.errors.full_messages_for(:expiration_date).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% days_until_expiration_class = "form-control" %>
    <% days_until_expiration_was_invalid = inventory_of_food_item.errors.include?(:days_until_expiration) %>

    <% if was_validated %>
      <% if days_until_expiration_was_invalid %>
        <% days_until_expiration_class << " is-invalid" %>
      <% else %>
        <% days_until_expiration_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :days_until_expiration %>
    <%= f.text_field :days_until_expiration, class: days_until_expiration_class, placeholder: "Enter days until expiration" %>
    <% if days_until_expiration_was_invalid %>
      <% inventory_of_food_item.errors.full_messages_for(:days_until_expiration).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% purchased_status_class = "form-control" %>
    <% purchased_status_was_invalid = inventory_of_food_item.errors.include?(:purchased_status) %>

    <% if was_validated %>
      <% if purchased_status_was_invalid %>
        <% purchased_status_class << " is-invalid" %>
      <% else %>
        <% purchased_status_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :purchased_status %>
    <%= f.select :purchased_status, options_for_select(InventoryOfFoodItem.purchased_statuses.keys), {}, class: "form-control" %>
    <% if purchased_status_was_invalid %>
      <% inventory_of_food_item.errors.full_messages_for(:purchased_status).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% food_name_class = "form-control" %>
    <% food_name_was_invalid = inventory_of_food_item.errors.include?(:food_name) %>

    <% if was_validated %>
      <% if food_name_was_invalid %>
        <% food_name_class << " is-invalid" %>
      <% else %>
        <% food_name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :food_name %>
    <%= f.text_field :food_name, class: food_name_class, placeholder: "Enter food name" %>
    <% if food_name_was_invalid %>
      <% inventory_of_food_item.errors.full_messages_for(:food_name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% note_class = "form-control" %>
    <% note_was_invalid = inventory_of_food_item.errors.include?(:note) %>

    <% if was_validated %>
      <% if note_was_invalid %>
        <% note_class << " is-invalid" %>
      <% else %>
        <% note_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :note %>
    <%= f.text_field :note, class: note_class, placeholder: "Enter note" %>
    <% if note_was_invalid %>
      <% inventory_of_food_item.errors.full_messages_for(:note).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/inventory_of_food_items/_inventory_of_food_item_recipe_ingredients.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Recipe Ingredients

    <a data-toggle="collapse" href="#inventory_of_food_item_recipe_ingredients_new_form">
      Add recipe ingredient
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @inventory_of_food_item.recipe_ingredients.each do |recipe_ingredient| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to recipe_ingredient, recipe_ingredient %>

        <%= link_to recipe_ingredient, method: :delete, data: { confirm: "Do you really want to delete this recipe_ingredient" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="inventory_of_food_item_recipe_ingredients_new_form">
        <%= render partial: "inventory_of_food_items/inventory_of_food_item_recipe_ingredients_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/inventory_of_food_items/_inventory_of_food_item_recipe_ingredients_new_form.html.erb
<%= form_with(model: @recipe_ingredient, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :recipe_id %>

    <%= f.collection_select :recipe_id, Recipe.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :food_id, value: @inventory_of_food_item.id %>

  <div class="form-group">
    <%= f.label :ingredient_name %>

    <%= f.text_field :ingredient_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :quantity %>

    <%= f.text_field :quantity, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :quantity_units %>

    <%= f.select :quantity_units, options_for_select(RecipeIngredient.quantity_units.keys), {}, class: "form-control" %>
  </div>

  <%= f.submit "Create recipe ingredient", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/inventory_of_food_items/_inventory_of_food_items_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "inventory_of_food_items_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :food_name_cont, "Food name contains" %>
    <%= f.text_field :food_name_cont, :class => "form-control", :placeholder => "Food name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :note_cont, "Note contains" %>
    <%= f.text_field :note_cont, :class => "form-control", :placeholder => "Note contains" %>
  </div>

  <div class="form-group">
    <%= f.label :days_until_expiration_cont, "Days until expiration contains" %>
    <%= f.text_field :days_until_expiration_cont, :class => "form-control", :placeholder => "Days until expiration contains" %>
  </div>

  <div class="form-group">
    <%= f.label :expiration_date, "Expiration date" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='expiration_dategteqPicker' data-target-input="nearest">
          <%= f.text_field :expiration_date_gteq, :class => "form-control datetimepicker-input", :placeholder => "Expiration date greater than or equal to", :data => {:target => '#expiration_dategteqPicker'} %>
          <div class="input-group-append" data-target='#expiration_dategteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='expiration_datelteqPicker' data-target-input="nearest">
          <%= f.text_field :expiration_date_lteq, :class => "form-control datetimepicker-input", :placeholder => "Expiration date less than or equal to", :data => {:target => '#expiration_datelteqPicker'} %>
          <div class="input-group-append" data-target='#expiration_datelteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#expiration_dategteqPicker').datetimepicker({
              format: 'MM/DD/YYYY'
          });
          $('#expiration_datelteqPicker').datetimepicker({
              useCurrent: false,
              format: 'MM/DD/YYYY'
          });
          $('#expiration_dategteqPicker').on("dp.change", function (e) {
              $('#expiration_datelteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#expiration_datelteqPicker').on("dp.change", function (e) {
              $('#expiration_dategteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :date_purchased, "Date purchased" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='date_purchasedgteqPicker' data-target-input="nearest">
          <%= f.text_field :date_purchased_gteq, :class => "form-control datetimepicker-input", :placeholder => "Date purchased greater than or equal to", :data => {:target => '#date_purchasedgteqPicker'} %>
          <div class="input-group-append" data-target='#date_purchasedgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='date_purchasedlteqPicker' data-target-input="nearest">
          <%= f.text_field :date_purchased_lteq, :class => "form-control datetimepicker-input", :placeholder => "Date purchased less than or equal to", :data => {:target => '#date_purchasedlteqPicker'} %>
          <div class="input-group-append" data-target='#date_purchasedlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#date_purchasedgteqPicker').datetimepicker({
              format: 'MM/DD/YYYY'
          });
          $('#date_purchasedlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'MM/DD/YYYY'
          });
          $('#date_purchasedgteqPicker').on("dp.change", function (e) {
              $('#date_purchasedlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#date_purchasedlteqPicker').on("dp.change", function (e) {
              $('#date_purchasedgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :created_at, "User Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='usergteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :user_created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "User Created at greater than or equal to", :data => {:target => '#usergteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#usergteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='userlteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :user_created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "User Created at less than or equal to", :data => {:target => '#userlteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#userlteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#usergteqcreated_atPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#userlteqcreated_atPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#usergteqcreated_atPicker').on("dp.change", function (e) {
              $('#userlteqcreated_atPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#userlteqcreated_atPicker').on("dp.change", function (e) {
              $('#usergteqcreated_atPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :recipe_ingredients_ingredient_name_cont, "Recipe ingredients ingredient_name contains" %>
    <%= f.text_field :recipe_ingredients_ingredient_name_cont, :class => "form-control", :placeholder => "Recipe ingredients ingredient_name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/inventory_of_food_items" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#inventory_of_food_items_filters">
  Show filters
</a>

app/views/inventory_of_food_items/_list_item.html.erb
<%= link_to inventory_of_food_item, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= inventory_of_food_item %>
    <small class="text-muted">
      <%= time_ago_in_words(inventory_of_food_item.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/inventory_of_food_items/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Inventory Of Food Item #<%= @inventory_of_food_item.id %>
      </h2>

      <div class="card-body">
        <%= render "form", inventory_of_food_item: @inventory_of_food_item %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/inventory_of_food_items/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Inventory Of Food Items

      <%= link_to new_inventory_of_food_item_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "inventory_of_food_items/inventory_of_food_items_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Inventory Of Food Items

        <%= link_to new_inventory_of_food_item_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @inventory_of_food_items, partial: "list_item", as: :inventory_of_food_item %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @inventory_of_food_items, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/inventory_of_food_items/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Inventory Of Food Item
      </h2>

      <div class="card-body">
        <%= render "form", inventory_of_food_item: @inventory_of_food_item %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/inventory_of_food_items/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @inventory_of_food_item, partial: "card", as: :inventory_of_food_item %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "inventory_of_food_items/inventory_of_food_item_recipe_ingredients" %>
  </div>
</div>